on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    steps:
    
    - name: Jira Login
      uses: atlassian/gajira-login@v2.0.0
  
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: https://netkiller.atlassian.net
        JIRA_USER_EMAIL: hailey.park@netkiller.com
        JIRA_API_TOKEN: pNmqgBaIFggREUvCOali2B90

    - name: Jira TODO
      uses: atlassian/gajira-todo@master
      with:
        project: GA
        issuetype: Task
        description: Created automatically via GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
