on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    
    name: Jira Example
    steps:

      - name: Login
        run:
          echo ${{ secrets.JIRA_BASE_URL }}
          

    
