on: push

name: Jira Example

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jira Example
    environment: production
    steps:
    - name: Jira Login
      uses: atlassian/gajira-login@v2.0.0
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        
   
    - name: Create
      id: create
      uses: atlassian/gajira-create@master
      with:
        project: TEST
        issuetype: Build
        summary: |
          Build completed for ${{ github.repository }}
        description: |
          Compare branch
        fields: '{"customfield_10171": "test"}'

    - name: Log created issue
      run: echo "Issue ${{ steps.create.outputs.issue }} was created"
